export const kanjiRadicals = [
    { id: 1, level: "N5", radikal: "一", arti: "Satu", contoh: "七, 上, 下" },
    { id: 2, level: "N5", radikal: "丨", arti: "Garis Vertikal", contoh: "中, 串" },
    { id: 3, level: "N5", radikal: "丶", arti: "Titik", contoh: "主, 丸" },
    { id: 4, level: "N5", radikal: "丿", arti: "Garis Miring", contoh: "久, 乏" },
    { id: 5, level: "N5", radikal: "二", arti: "Dua", contoh: "五, 互" },
    { id: 6, level: "N5", radikal: "人 (亻)", arti: "Orang", contoh: "休, 何, 体" },
    { id: 7, level: "N5", radikal: "儿", arti: "Kaki Manusia", contoh: "兄, 元" },
    { id: 8, level: "N5", radikal: "入", arti: "Masuk", contoh: "込, 入" },
    { id: 9, level: "N5", radikal: "八", arti: "Delapan", contoh: "分, 公" },
    { id: 10, level: "N5", radikal: "冂", arti: "Penutup/Tirai", contoh: "内, 再" },
    { id: 11, level: "N5", radikal: "冫", arti: "Es", contoh: "冷, 冬" },
    { id: 12, level: "N5", radikal: "几", arti: "Meja", contoh: "机, 凡" },
    { id: 13, level: "N5", radikal: "口", arti: "Mulut", contoh: "名, 右, 味" },
    { id: 14, level: "N5", radikal: "囗", arti: "Kotak", contoh: "国, 四" },
    { id: 15, level: "N5", radikal: "土", arti: "Tanah", contoh: "地, 場, 坂" },
    { id: 16, level: "N5", radikal: "夕", arti: "Malam", contoh: "外, 多" },
    { id: 17, level: "N5", radikal: "大", arti: "Besar", contoh: "天, 太, 夫" },
    { id: 18, level: "N5", radikal: "女", arti: "Perempuan", contoh: "姉, 妹, 好" },
    { id: 19, level: "N5", radikal: "子", arti: "Anak", contoh: "学, 字, 孫" },
    { id: 20, level: "N5", radikal: "宀", arti: "Atap", contoh: "家, 安, 室" },
    { id: 21, level: "N5", radikal: "寸", arti: "Ukuran", contoh: "対, 寺" },
    { id: 22, level: "N5", radikal: "小", arti: "Kecil", contoh: "少, 直" },
    { id: 23, level: "N5", radikal: "山", arti: "Gunung", contoh: "岩, 岸, 峰" },
    { id: 24, level: "N5", radikal: "工", arti: "Tukang/Kerja", contoh: "左, 工" },
    { id: 25, level: "N5", radikal: "巾", arti: "Kain", contoh: "市, 帰" },
    { id: 26, level: "N5", radikal: "干", arti: "Kering", contoh: "平, 年" },
    { id: 27, level: "N5", radikal: "幺", arti: "Kecil/Pendek", contoh: "幻, 幼" },
    { id: 28, level: "N5", radikal: "广", arti: "Gedung/Toko", contoh: "店, 度" },
    { id: 29, level: "N5", radikal: "心 (忄)", arti: "Hati", contoh: "思, 急, 感" },
    { id: 30, level: "N5", radikal: "戈", arti: "Tombak", contoh: "成, 我" },
    { id: 31, level: "N5", radikal: "手 (扌)", arti: "Tangan", contoh: "持, 打, 指" },
    { id: 32, level: "N5", radikal: "支", arti: "Cabang", contoh: "技, 枝" },
    { id: 33, level: "N5", radikal: "文", arti: "Tulisan", contoh: "校, 文" },
    { id: 34, level: "N5", radikal: "斗", arti: "Gayung", contoh: "料, 科" },
    { id: 35, level: "N5", radikal: "日", arti: "Matahari", contoh: "明, 時, 昨" },
    { id: 36, level: "N5", radikal: "月", arti: "Bulan", contoh: "朝, 期, 青" },
    { id: 37, level: "N5", radikal: "木", arti: "Pohon", contoh: "本, 林, 森" },
    { id: 38, level: "N5", radikal: "欠", arti: "Kurang", contoh: "歌, 次" },
    { id: 39, level: "N5", radikal: "止", arti: "Berhenti", contoh: "歩, 正" },
    { id: 40, level: "N5", radikal: "比", arti: "Membandingkan", contoh: "皆, 此" },
    { id: 41, level: "N4", radikal: "水 (氵)", arti: "Air", contoh: "池, 海, 泳" },
    { id: 42, level: "N4", radikal: "火 (灬)", arti: "Api", contoh: "熱, 焼" },
    { id: 43, level: "N4", radikal: "爪", arti: "Cakar", contoh: "受, 采" },
    { id: 44, level: "N4", radikal: "父", arti: "Ayah", contoh: "爺" },
    { id: 45, level: "N4", radikal: "片", arti: "Potongan", contoh: "版, 牌" },
    { id: 46, level: "N4", radikal: "犬 (犭)", arti: "Anjing", contoh: "猫, 独" },
    { id: 47, level: "N4", radikal: "王", arti: "Raja/Permata", contoh: "現, 球" },
    { id: 48, level: "N4", radikal: "糸 (纟)", arti: "Benang", contoh: "紙, 結, 給" },
    { id: 49, level: "N4", radikal: "耳", arti: "Telinga", contoh: "聞, 職" },
    { id: 50, level: "N4", radikal: "見", arti: "Melihat", contoh: "覚, 観" }
];
